// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"Community_Basic","status":true,"description":"Plugin used to set basic parameters.","parameters":{"cacheLimit":"10","screenWidth":"816","screenHeight":"624","changeWindowWidthTo":"816","changeWindowHeightTo":"624","renderingMode":"auto","alwaysDash":"off"}},
{"name":"FC_AboutLowerBodyMV","status":true,"description":"Adjust the opacity and depth of the lower part of the body that is hidden by bushes, etc.","parameters":{"LowerBodyOpacity":"0","size":"24"}},
{"name":"FC_DontTrimMV","status":true,"description":"Prevent the battle background from being cropped, regardless of whether it is front or side view.","parameters":{}},
{"name":"FC_NoBattleLogMV","status":true,"description":"Hides the battle log displayed at the top of the battle screen.","parameters":{}},
{"name":"FC_SVCharaPositionMV","status":true,"description":"Adjust the position of the SV Actors.","parameters":{"x":"653","spaceX":"0","y":"24","spaceY":"12"}},
{"name":"FC_WindowOpacity","status":true,"description":"Adjusts the transparency of the window.","parameters":{"Opacity":"255"}},
{"name":"FC_AjustTerrainMV","status":true,"description":"Optimize the auto-selected battle background in the field map.","parameters":{"MakeBlack":"0"}},
{"name":"FC_ShadowPenMV","status":true,"description":"Adjusts the opacity of the shadow pen.","parameters":{"Opacity":"0"}},
{"name":"FC_AjustFontMV","status":true,"description":"Adjust around the font.","parameters":{"NoOutline":"1","NoGauge":"0","SystemIsNomal":"0","CrisisIsNomal":"0","DeathIsNomal":"0","GaugeBackIsBlack":"0","HpGaugeIsNomal":"0","MpGaugeIsNomal":"0","MpCostIsNomal":"0","PowerUpIsNomal":"0","PowerDownIsNomal":"0","TpGaugeIsNomal":"0","TpCostIsNomal":"0"}},
{"name":"JRPGFR_ActorsName","status":true,"description":"Affiche le nom du personnage sous la fenêtre de dialogue en utilisant le champ Note de l'événement.","parameters":{}}
];
